### ISSUE TITLE
Stops working after running webpack task runner

### ISSUE THREAD

**Issue by richardgroenewegen** [dsuryd/dotnetify-react-demo-vs2017#1]
Hi, first of all I'm just amazed by the simplicity (from a user perspective). The most promising thing I have seen for web development.  I'm struggling a bit with webpack.  Perhaps you can help.  When I run LiveCharts directly form your project, it works fine.  But after I run the webpack task runner (Run - Development), it no longer works, on any browser (just a blank screen).

The bundle.js is now significantly bigger.  It was 329KB and became 1384KB.  But I can't tell what the issue is or where to look.

The routing demo also give me a blank screen, both before and after runn the task runner.

The Hello World application is the only one that works entirely without issues, both before and after unning webpack.

Any ideas?

**Comment by dsuryd** [comment]
Hi, thanks for your feedback!
I was able to reproduce what you saw.  To fix, add this inside the head tag of index.html:
`   <meta http-equiv="content-type" content="text/html; charset=UTF8">`

The webpack config that was checked in here doesn't do minification.  To minify, add this to the plugin array in webpack.config.js:
`new webpack.optimize.UglifyJsPlugin({ minimize: true })`

**Comment by richardgroenewegen** [comment]
Thanks so much. That works perfectly for the LiveChart demo.  Now, I'm looking to find out why I'm not getting any results on the routing demo.  

The page it serves on `/Index` looks like this:
```
<html><head></head>
<body>
<pre style="word-wrap: break-word; white-space: pre-wrap;"></pre>
</body></html>
```

If I figure out what's not working I'll revert here.

**Comment by dsuryd** [comment]
Try clearing your browser cache. I had to do that when I ran routing right after livechart from vs2017. If you still have problem, send me the browser console log.

**Comment by richardgroenewegen** [comment]
I tried on a different system (now both windows 10 and windows 7) and every single browser.  And I never anything good. For chrome, firefox, etc it is a blank page.  I get an error with Internet Explorer.

Firefox log (on a fresh install of firefox):
```
reflow: 0.65ms
reflow: 1.04ms
GET 
http://localhost:61200/index [HTTP/1.1 500 Internal Server Error 107ms]
Headers
Response
Content-Length0DateSun, 25 Jun 2017 20:05:04 GMTServerKestrelX-Powered-ByASP.NETX-SourceFiles=?UTF-8?B?QzpcQ1xkb3RuZXRpZnktcmVhY3QtZGVtby12czIwMTctbWFzdGVyXFJvdXRpbmdcaW5kZXg=?=
Accepttext/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5Cache-Controlno-cacheConnectionkeep-aliveHostlocalhost:61200Pragmano-cacheUpgrade-Insecure-Requests1User-AgentMozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

reflow: 0.49ms
reflow: 0.13ms function _calcMouseTargetRect, tabbrowser.xml line 7619
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.  index
reflow: 0.22ms
reflow: 0.21ms
```

Internet explorer 11 shows:

```
HTML1300: Navigation occurred. File: http_500.htm
HTML1524: Invalid HTML5 DOCTYPE. Consider using the interoperable form "<!DOCTYPE html>".
File: http_500.htm, Line: 1, Column: 1
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: http_500.htm
```

**Comment by dsuryd** [comment]
The routing demo uses server side rendering which requires nodejs. Was it installed in your system?

**Comment by richardgroenewegen** [comment]
OK, thanks.  I indeed dit not have nodejs. Now working
