### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by DHirani** [dsuryd/dotnetify-react-demo-vs2017#10]
Is it possible to add support for TypeScript?

**Comment by dsuryd** [comment]
Typescript typings are available here: [https://github.com/dsuryd/dotNetify/tree/master/dist/typings](https://github.com/dsuryd/dotNetify/tree/master/dist/typings)

**Comment by DHirani** [comment]
Thanks, do you have an example using it?

**Comment by dsuryd** [comment]
No, I don't currently use Typescript for React, but you can check with the person that provided me those files ([dotNetify issue #46](https://github.com/dsuryd/dotNetify/issues/46)).  His github has dotNetify app in Typescript.

**Comment by DHirani** [comment]
Thank you
