### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by forconz** [dsuryd/dotnetify-react-demo-vs2017#11]
dotnet restore
dotnet build
npm install
npm start

https://github.com/dsuryd/dotnetify-react-demo
**The code work well.I saw the ** 
https://github.com/dsuryd/dotnetify-react-demo-vs2017
**I get  npm ERR! missing script: start**

PS C:\Users\lenovo> cd D:\Marketer\test\react\HelloWorld
PS D:\Marketer\test\react\HelloWorld> dotnet restore
  Restoring packages for D:\Marketer\test\react\HelloWorld\HelloWorld.csproj...
  Generating MSBuild file D:\Marketer\test\react\HelloWorld\obj\HelloWorld.csproj.nuget.g.props.
  Generating MSBuild file D:\Marketer\test\react\HelloWorld\obj\HelloWorld.csproj.nuget.g.targets.
  Restore completed in 2.18 sec for D:\Marketer\test\react\HelloWorld\HelloWorld.csproj.
PS D:\Marketer\test\react\HelloWorld> dotnet build
用于 .NET Core 的 Microsoft (R) 生成引擎版本 15.5.179.9764
版权所有(C) Microsoft Corporation。保留所有权利。

  Restore completed in 68.02 ms for D:\Marketer\test\react\HelloWorld\HelloWorld.csproj.
  HelloWorld -> D:\Marketer\test\react\HelloWorld\bin\Debug\netcoreapp2.0\HelloWorld.dll

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:04.58
PS D:\Marketer\test\react\HelloWorld> npm install babel-core -g
+ babel-core@6.26.0
removed 81 packages and updated 51 packages in 14.395s
PS D:\Marketer\test\react\HelloWorld> npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: p
lease read babeljs.io/env to update!
[ .................] / fetchMetadata: WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recom
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-D8Z9fBQYJd6
UKC3VNr7GubzoYKs= integrity checksum failed when using sha1: wanted sha1-D8Z9fBQYJd6UKC3VNr7GubzoYKs= but got sha512-4AH
6Z5fzNNBcH+6XDMfA/BTt87skxqJlO0lAh3Dker5zThcAxG6mKz+iGu308UKoPPQ8Dcqx/4JhujzltRa+hQ==. (4142 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\Marketer\test\react\HelloWorld\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN aspnet-webpack@2.0.1 requires a peer of webpack@^1.13.2 || ^2.1.0-beta but none is installed. You must install
peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})

added 605 packages in 31.139s
PS D:\Marketer\test\react\HelloWorld> npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2018-03-02T14_31_51_461Z-debug.log

The content of 2018-03-02T14_31_51_461Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (D:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (D:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)
5 verbose cwd D:\Marketer\test\react\HelloWorld
6 verbose Windows_NT 10.0.14393
7 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v9.2.0
9 verbose npm  v5.5.1
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by forconz** [comment]
ReactTemplate project worked well.

**Comment by dsuryd** [comment]
Use Visual Studio 2017 to run dotnetify-react-demo-vs2017 projects.  Don't use npm.
