### ISSUE TITLE
Bundle minification for release

### ISSUE THREAD

**Issue by RobertTheGrey** [dsuryd/dotnetify-react-demo-vs2017#14]
Great work on the new template: `DotNetify.React.Template` - just wondering what the best way is to go about building something on top of dotnetify, and then triggering all the bundle minification etc. that we usually do on our React projects. I can go and do it myself the same way I have for other React/Node projects using webpack, but was just wondering if you already have a strategy or sample that does this on Release and Deploy to save time. If not, no worries, I'm happy to try it out myself and contribute the result back into the Template.

I can see the commented out line in the `webpack.config.js` which will uglify, but it's more about keeping the code as it is for development, and having it know about minification as a deployment/release step

Cheers and GREAT framework - I'm loving the SignalR integrations!

**Comment by dsuryd** [comment]
The template still needs more work in that regard.  I don't have a definite strategy yet, other than the idea to make it simple like create-react-app / angular-cli.   If you have the experience to contribute, I'd be happy if you would!

**Comment by RobertTheGrey** [comment]
Thanks - no probem. I'll take a look when I get close to a release soon

**Comment by dsuryd** [comment]
Not sure if you're still working on this; so I'm closing this.  Feel free to reopen.

**Comment by RobertTheGrey** [comment]
I tend to use the later version no with `create-react-app` scripts so minifying comes out the box then when setting it to production, so I don't really have a need for this anymore. Thanks for checking though!
