### ISSUE TITLE
I want to create a chat project using dotnetify

### ISSUE THREAD

**Issue by thiemdp** [dsuryd/dotnetify-react-demo-vs2017#18]
@dsuryd  
I want to create a chat project using dotnetify.
But I do not know how to send messages to other users.
can you give me the document of dotnetify or Do you have a simple example of this? 
thank you very much

**Comment by dsuryd** [comment]
The closest example to what you want to do is this: https://github.com/dsuryd/dotnetify-knockout-demo/tree/master/BunnyPen.   The client-side isn't React, but the same back-end code pattern applies.
