### ISSUE TITLE
FuseBox support

### ISSUE THREAD

**Issue by MrFoxPro** [dsuryd/dotnetify-react-demo-vs2017#23]
I dived into FuseBox tool, and its really more  easier than webpack. I think it would be nice to make fusebox template.
https://github.com/fuse-box/fuse-box/issues/845

**Comment by dsuryd** [comment]
I was actually thinking of looking at Parcel.   But Webpack 4 boasts no
config needed, and it’s still very popular to not be supported.   The last
thing I want to do is to maintain support of various build tools.

**Comment by dsuryd** [comment]
I'll close this as right now there's no intention to support more than one build tool.
