### ISSUE TITLE
Returning FileContentResult and Uploading File

### ISSUE THREAD

**Issue by cvalarcon** [dsuryd/dotnetify-react-demo-vs2017#24]
Amazing work on the template, it's truly made my spa project simple and concise.  I do have an issue which I cannot overcome.  Given that the VM classes does not inherit from Controller base and therefore no ability to return an ActionResult, what would be the best way to download (return File) or upload (consume Form.File) files.  I've tried several ways including Func delegates with no luck.  You're assistance would be very much appreciated, thanks in advance!

**Comment by dsuryd** [comment]
I would recommend you still use Web API to transfer files, just because it has more mature/robust handling.  You can provide the response back to the client-side component and relayed back to the server-side view model.

**Comment by cvalarcon** [comment]
Ah right, should have thought of that but I suppose my mindset was on MVC
and using some type of Controller action.  Yes, thank you that should work
quite well!
