### ISSUE TITLE
Live Chart: 405 Status (Method Not Allowed)

### ISSUE THREAD

**Issue by fastrocket** [dsuryd/dotnetify-react-demo-vs2017#27]
Steps to repro:

1. git clone https://github.com/dsuryd/dotnetify-react-demo-vs2017.git
2. Launch VS2017 with the solution file in LiveChart/
3. Right-click on project.json and select Restore Packages
4. Run in Debug or Release mode (with IIS Express or LiveChart with Chrome)
5. See a blank chart in web browser. View the javascript console to see:  

> OPTIONS http://localhost:61201/dotnetify 405 (Method Not Allowed)

![image](https://user-images.githubusercontent.com/10687661/47852574-d5b9d900-dda1-11e8-8fea-0424f1582a0e.png)

**Comment by dsuryd** [comment]
The example was outdated.  The latest should not give you any more problem.

**Comment by fastrocket** [comment]
That fixed it, thanks! (There are problems with the other two React template projects, I'll post a new ticket)
