### ISSUE TITLE
Best way to access user identity claim in app?

### ISSUE THREAD

**Issue by behnam-basketasia** [dsuryd/dotnetify-react-demo-vs2017#33]
Hi,

I'm trying to access OpenID object within VM (Example `Formate Table` or `Table Page` at ) .

Basically I have used below to get UserId but a lot of time I'm getting `null` value:

```
using DotNetify;
using DotNetify.Security;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Net;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;

class FormPage
    public FormPage(IPrincipalAccessor principalAccessor){
           ClaimsIdentity userIdentity = principalAccessor.Principal.Identity as ClaimsIdentity;
            
            // appUserId is getting null here (sometimes)
            ulong appUserId = userIdentity.GetUserId<ulong>();
            
    }
}
```

UserIdentity being:
```
using System;
using System.Globalization;
using System.Security.Claims;
using System.Security.Principal;

namespace Bot.Common.Utilities
{
    public static class IdentityExtensions
    {
        public static T GetUserId<T>(this IIdentity identity) where T : IConvertible
        {
            var userId = identity?.GetUserId();
            return userId.HasValue()
                ? (T)Convert.ChangeType(userId, typeof(T), CultureInfo.InvariantCulture)
                : default;
        }

}
```

**Comment by dsuryd** [comment]
The code seems correct.  You might want to make sure at the time the constructor is called the user's already authenticated.

**Comment by ensemblebd** [comment]
That's how I'm doing it too - works good. 
I used the sample's AuthServer middleware (JWT tokens) and apply the SignInManager.PasswordSignInAsync() on the form submit.
From that we apply identity claims using the middleware for UserClaimsPrincipalFactory. 
That gives the AuthServer middleware the ability to start with context.User.Claims as a list, and apply it's JWT token on top of that. 
Can just do a Linq AddRange for any custom dbcontext claims.. (in my case, groups and roles)

IPrincipalAccessor works great for constructors via DI, but dsuryd also gave a sample of the IVMFilter which too can access the vmContext.HubContext.Principal , and inject that into your BaseVM's using an exposed function.
