### ISSUE TITLE
Change route with use of routing api 

### ISSUE THREAD

**Issue by behnam-basketasia** [dsuryd/dotnetify-react-demo-vs2017#34]
In my react project that was build with dotnetify, I want to redirect to a specific route from BackEnd. I handle all my routes with "react-router". 
In `index.js` i use `BrowserRouter` that wrapped all my route.   
```
render(
    <Provider store={store}>
        <BrowserRouter>
            <App/>
        </BrowserRouter>
    </Provider>,
    document.getElementById('App')
);
```
and `App.js` is like below:
```
<Switch>
       <Route path="/page1"  component={page1}/>
       <Route path="/page2"  component={Home2}/>
       <Route path="/page3" component={Home}/>
</Switch>
```
now i want to change my route with `Routing Api` that introduce in `dotnetify`. as in document said, i add my component to windows variable in `App.js` 
```
Object.assign(window, { Page1, Page2 });
```
in `page1.cs`, the route was register in constructor of a class that inherited from `IRoutable` and send a route to the client:
```
 this.RegisterRoutes("/", new List<RouteTemplate>
            {
                new RouteTemplate("Page1") { UrlPattern = "page1" },
            });

            RedirectUrl = this.GetRoute("Page1");
            Changed(nameof(RedirectUrl));
```
in page1 that in constructor  connected to its viewmodel insert a routelink to change the route:
```
 <RouteLink vm={this.vm} route={RedirectUrl}>
                    click
 </RouteLink>
```
but by clicking on this an error was occured:
```
   You should not use <Route> or withRouter() outside a <Router>
```
what is the best way to handle redirect from backend nad how can i handle it?

**Comment by dsuryd** [comment]
That error isn't from dotNetify.  Start from this template to make sure the routing is implemented correctly.

**Comment by behnam-basketasia** [comment]
can we user dotnetify routing api and react router with each other in one project?
and how about redux when we use dotnetify routing api?
as i now, in routing api, we assign component to the window object and it load every time that it is called, and if we have provide and its store for redux, can we use state in redux in the route that load from this api?
thank for this great project

**Comment by behnam-basketasia** [comment]
when i use boot react router and  routing api, and change route with routing api(RouteLink), i faced with this problem:
```
index.js:1437 Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by React and is not a top-level container. You may have accidentally passed in a React root node instead of its container.
console.<computed> @ index.js:1437
warningWithoutStack @ react-dom.development.js:520
unmountComponentAtNode @ react-dom.development.js:22275
createViewFunc @ dotnetify-react.js:2084
(anonymous) @ dotnetify-react.js:2101
loadReactView @ dotnetify-react.js:2068
loadView @ dotnetify-react.js:2038
routeTo @ dotnetify-react.js:1750
(anonymous) @ dotnetify-react.js:1578
(anonymous) @ dotnetify-react.js:2449
run @ dotnetify-react.js:2356
dispatch @ dotnetify-react.js:2249
pushState @ dotnetify-react.js:2153
pushState @ dotnetify-react.js:2478
(anonymous) @ dotnetify-react.js:1514
setTimeout (async)
handleRoute @ dotnetify-react.js:1513
iVM.$handleRoute @ dotnetify-react.js:2567
handleClick @ dotnetify-react.js:1032
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:265
executeDispatch @ react-dom.development.js:571
executeDispatchesInOrder @ react-dom.development.js:596
executeDispatchesAndRelease @ react-dom.development.js:695
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:704
forEachAccumulated @ react-dom.development.js:676
runEventsInBatch @ react-dom.development.js:844
runExtractedEventsInBatch @ react-dom.development.js:852
handleTopLevel @ react-dom.development.js:5030
batchedUpdates$1 @ react-dom.development.js:21469
batchedUpdates @ react-dom.development.js:2247
dispatchEvent @ react-dom.development.js:5110
(anonymous) @ react-dom.development.js:21526
unstable_runWithPriority @ scheduler.development.js:255
interactiveUpdates$1 @ react-dom.development.js:21525
interactiveUpdates @ react-dom.development.js:2268
dispatchInteractiveEvent @ react-dom.development.js:5086
index.js:1437 Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.
```

**Comment by dsuryd** [comment]
>can we user dotnetify routing api and react router with each other in one project?
and how about redux when we use dotnetify routing api?

DotNetify routing is its own routing system, and wasn't designed to complement react-router or redux.  It's probably best to just choose one over the other instead of trying to mix them together.   

With that said, if you want to choose dotNetify routing but can't because it's missing some features you need, we can start the discussion on what those features are.

**Comment by behnam-basketasia** [comment]
one of those thing is that when user try to reach a page that could not be found on the routing api system, user must be reached to 404 page, how can we handle 404 page in this system?

**Comment by dsuryd** [comment]
That's one of the missing feature.  I suggest you create an issue in the main dotNetify github for each one you found.  It will help me to plan and others to keep track and maybe contribute.
