### ISSUE TITLE
Can't build ReactTemplateTS

### ISSUE THREAD

**Issue by stluong** [dsuryd/dotnetify-react-demo-vs2017#35]
Not sure what is going, but i can't build the project
Have tried: npm install and failed

**Comment by dsuryd** [comment]
What's the error?

**Comment by stluong** [comment]
[2019-07-17T21_38_07_370Z-debug.log](https://github.com/dsuryd/dotnetify-react-demo-vs2017/files/3403918/2019-07-17T21_38_07_370Z-debug.log)

**Comment by stluong** [comment]
i maybe do something wrong! Here are some step to run your solution that i have tried
1. Open Content folder and run
npm install
2. npm run build
3. Open solution with Visual Studio 2017, run, but error

**Comment by stluong** [comment]
![image](https://user-images.githubusercontent.com/4374191/61414105-cd171d80-a8b2-11e9-9709-6ad7a59426b3.png)

**Comment by dsuryd** [comment]
Can you try the original ReactTemplate?  The steps are just: npm i, followed by dotnet run.   The ReactTemplateTS was from a PR contributor and I don't really maintain it.

**Comment by stluong** [comment]
got ya, thanks for helping:)

**Comment by stluong** [comment]
yeah, it is working now
