### ISSUE TITLE
deploy as selfhosted .exe 

### ISSUE THREAD

**Issue by DG4ever** [dsuryd/dotnetify-react-demo-vs2017#6]
I am trying to publish this example as a self hosted .exe.
I am publishing the project with: `dotnet publish -c release -r win7-x64`
The .exe is generated but when running it crashes at `BuildWebHost(args).Run();`
I also tried running the .dll with `dotnet projectname.dll` inside the release folder but that produces the same error.
Running the project with `dotnet run` works as expected.
Do you have an advice what I might doing wrong?

**Comment by dsuryd** [comment]
Which example?  I have tested both HelloWorld and LiveChart. One or both will require you to run 'npm i' on the publish folder and then copy webpack.config.js in there.  I've tested them on Win10, works fine.  If you've done all these things,  perhaps it's something to do with Win7.

**Comment by dsuryd** [comment]
Successfully tested the `ReactTemplate` on a Win7 using the following steps:
-  dotnet publish -c release -r win7-x64
- npm i 
- copy `webpack.config.js` 
- copy `clients` folder
- dotnet MyApp.dll

**Comment by DG4ever** [comment]
Thank you for the fast response. Now it is working as expected.
